name: Release
on:
  workflow_dispatch:
    branches: [ master ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: |
            6
            7
            8

      - name: Build
        run: |
            dotnet pack -c release -o nuget -p:Version=1.60.0.${{ github.run_number }}
            dotnet nuget push "nuget/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
        